name: Deploy DynamoDB CRUD API


#controls when the action will run. Triggers the workflow on push or pull
#events but only for the main branch
on: 
  push:
    branches: [ main ]

# a workflow run is made up of one or more jobs that can run sequentially
jobs:
  #this workflow contains a single job called "deploy"
  deploy:
    name: deploy

    #the type of the runner the job will run on
    runs-on: ubuntu-latest

    # steps represent a sequence of task that be executed
    steps:
      #checks out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with: 
          path: '**/node_modules'
          key: ${{runner.os}}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          #serverless access key ${{ secrets.SERVERLESS_ACCESS_KEY }}
          #or if using aws creds directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}